/* Siitperf is an RFC 8219 SIIT (stateless NAT64) tester written in C++ using DPDK
/* Siitperf is an RFC 8219 SIIT (stateless NAT64) tester written in C++ using DPDK
 * Variable port feature is also added to comply with RFC 4814,
 * for more information: https://tools.ietf.org/html/rfc4814#section-4.5
 *
 *  Copyright (C) 2019-2020 Gabor Lencse
 *
 *  This file is part of siitperf.
 *
 *  Siitperf is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Siitperf is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with siitperf.  If not, see <https://www.gnu.org/licenses/>.
 */

#define CONFIGFILE "siitperf.conf"	/* name of the configuration file */
#define LINELEN 100             /* max. line length, used by config file reader */
#define LEFTPORT 0		/* port ID of the "Left" port */
#define RIGHTPORT 1		/* port ID of the "Right" port */
#define MAX_PORT_TRIALS 10      /* rte_eth_link_get() is attempted maximum so many times, and error is reported if still unsuccessful */
#define START_DELAY 2000        /* Delay (ms) before senders start sending, used for synchronized start. Beware that DUT NICs need time to get ready! */
#define TOLERANCE 1.00001       /* Maximum allowed time inaccuracy, 1.00001 allows 0.001% more time for sending */
#define N 40			/* used for PDV and varport: all frames exist is N copies to mitigate the problem of write after send */

// the below values are used, when unique port number combinations are generated by random permutation
// before changing their values, please fully understand, how they are used
// constants for Warnings about unoptimal solutions for ensuring unique port numbers
#define CHECKING_VERY_LOW 2	/* collision and new generation with more than 50% probability */
#define CHECKING_A_BIT_LOW 4	/* collision and new generation with more than 25% probability */
#define SIGNIFICANT_NUMBER 100000000 /* the number of port number combinations to pre-generate is significant */
#define RAND_PERM_A_BIT_HIGH 5  /* generates 5 times more uniqe port pairs than needed */
#define RAND_PERM_VERY_HIGH 10  /* generates 10 times more uniqe port pairs than needed */

// values taken from DPDK sample programs
#define MAX_PKT_BURST 32        /* Maximum burst size for rte_eth_rx_burst() */
#define PKTPOOL_CACHE 32        /* used by rte_pktmbuf_pool_create() */
#define PORT_RX_QUEUE_SIZE 1024	
#define PORT_TX_QUEUE_SIZE 1024
